# Generated by Django 3.1.3 on 2020-11-12 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Баннер')),
            ],
        ),
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('water_resist', models.CharField(max_length=50, verbose_name='Стандарт защиты от воды')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('display_type', models.CharField(max_length=50, verbose_name='Тип экрана')),
                ('display_diagonal', models.FloatField(verbose_name='Диагональ экрана')),
                ('main_camera', models.IntegerField(verbose_name='Разрешение основной камеры')),
                ('front_camera', models.IntegerField(verbose_name='Разрешение фронтальной камеры')),
                ('cpu', models.CharField(max_length=50, verbose_name='Процессор')),
                ('ram', models.IntegerField(verbose_name='Оперативная память')),
                ('ssd', models.IntegerField(verbose_name='Встроенная память')),
                ('system', models.CharField(max_length=50, verbose_name='Платформа')),
            ],
            bases=('store.product',),
        ),
    ]
