# Generated by Django 3.1.3 on 2020-11-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_comment'),
        ('store', '0005_cart'),
    ]

    operations = [
    ]
